In [ ]:
#Description: this program will detect whether an email is spam(1) or not spam(0)

In [1]:
#Import libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [5]:
#Loading the data
from google.colab import files
uploaded = files.upload()

Saving completeSpamAssassin.csv to completeSpamAssassin (1).csv


In [6]:
#Read the CSV file
df = pd.read_csv('completeSpamAssassin.csv')

#Print the first 5 rows
df.head(5)

Unnamed: 0                                               Body  Label
0           0  \nSave up to 70% on Life Insurance.\nWhy Spend...      1
1           1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
2           2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
3           3  ##############################################...      1
4           4  I thought you might like these:\n1) Slim Down ...      1

In [7]:
#Get the shape of the dataset (Get number of rows and columns)
df.shape

(6046, 3)

In [8]:
#Get the column names
df.columns

Index(['Unnamed: 0', 'Body', 'Label'], dtype='object')

In [9]:
#Check for duplicate data and remove them
df.drop_duplicates(inplace = True)

In [10]:
#Show new shape of the data set to check if there were any duplicates
df.shape

(6046, 3)

In [13]:
#Show number of missing data (NAN, NaN, na) for each column in the data set
df.isnull().sum()

Unnamed: 0    0
Body          1
Label         0
dtype: int64

In [16]:
#Remove the row of the missing data
df.dropna(inplace = True)

In [17]:
#Show number of missing data (NAN, NaN, na) for each column in the data set
df.isnull().sum()

Unnamed: 0    0
Body          0
Label         0
dtype: int64

In [18]:
#download the stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [28]:
def process_text(text):
  #1 remove punctuation
  #2 remove stopwords
  #3 return a list of clean rext words

  #1
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  #2
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  #3
  return clean_words

In [32]:
#show the tokenization (a list of tokens)
df['Body'].head().apply(process_text)

0    [Save, 70, Life, Insurance, Spend, ToLife, Quo...
1    [1, Fight, Risk, Cancer, httpwwwadclickwspcfmo...
2    [1, Fight, Risk, Cancer, httpwwwadclickwspcfmo...
3    [Adult, Club, Offers, FREE, Membership, INSTAN...
4    [thought, might, like, 1, Slim, Guaranteed, lo...
Name: Body, dtype: object

In [33]:
#Convert a colection of text to a matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['Body'])

In [34]:
#Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(messages_bow, df['Label'], test_size = 0.2 , random_state = 0)

In [35]:
#Get the shape of messages_bow
messages_bow.shape

(6045, 104176)

In [36]:
#Create and train the Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, Y_train)

In [38]:
#Print predictions
print(classifier.predict(X_train))

#Print actual Values
print(Y_train.values)

[0 0 0 ... 1 0 0]
[0 0 0 ... 1 0 0]


In [41]:
#Evaluating the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
prediction = classifier.predict(X_train)
print(classification_report(Y_train, prediction))
print()
print('Confusion Matrix: \n', confusion_matrix(Y_train, prediction))
print()
print('Prediction: ', accuracy_score(Y_train, prediction))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97      3315
           1       0.90      0.99      0.95      1521

    accuracy                           0.96      4836
   macro avg       0.95      0.97      0.96      4836
weighted avg       0.97      0.96      0.96      4836


Confusion Matrix: 
 [[3150  165]
 [  10 1511]]

Prediction:  0.9638130686517783


In [42]:
#Print predictions
print(classifier.predict(X_test))

#Print actual Values
print(Y_test.values)

[1 0 1 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [43]:
#Evaluating the model on the test data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
prediction = classifier.predict(X_test)
print(classification_report(Y_test, prediction))
print()
print('Confusion Matrix: \n', confusion_matrix(Y_test, prediction))
print()
print('Prediction: ', accuracy_score(Y_test, prediction))

              precision    recall  f1-score   support

           0       0.99      0.95      0.97       835
           1       0.89      0.98      0.93       374

    accuracy                           0.96      1209
   macro avg       0.94      0.96      0.95      1209
weighted avg       0.96      0.96      0.96      1209


Confusion Matrix: 
 [[790  45]
 [  8 366]]

Prediction:  0.9561621174524401
